package com.bbl.boxtv.launcher

import android.app.Activity
import android.app.AlertDialog
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.pm.PackageInstaller
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.drawable.BitmapDrawable
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.provider.Settings
import android.view.Gravity
import android.view.inputmethod.InputMethodManager
import android.widget.*
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID
import java.util.concurrent.Executors

class MainActivity:Activity(){
 private val executor=Executors.newSingleThreadExecutor();private val handler=Handler(Looper.getMainLooper());private lateinit var root:LinearLayout;private lateinit var title:TextView;private lateinit var status:TextView;private lateinit var clock:TextView;private lateinit var logo:ImageView;private lateinit var deviceId:String;private val prefs by lazy{getSharedPreferences("bbl",Context.MODE_PRIVATE)};private var currentApps:List<RemoteApp> = emptyList();private var installBusy=false;private var lastMessage="";private var lastWallpaper="";private var lastLogo=""
 private val periodicSync=object:Runnable{override fun run(){if(savedToken().isNotBlank())sync();handler.postDelayed(this,60000L)}};private val clockTick=object:Runnable{override fun run(){if(::clock.isInitialized)clock.text=SimpleDateFormat("dd/MM/yyyy  HH:mm",Locale("pt","BR")).format(Date());handler.postDelayed(this,30000L)}}
 override fun onCreate(b:Bundle?){super.onCreate(b);deviceId=DeviceIdentity.get(this);buildUi();clockTick.run();if(savedToken().isBlank())showActivation()else sync()};override fun onResume(){super.onResume();installBusy=false;handler.removeCallbacks(periodicSync);if(::deviceId.isInitialized&&savedToken().isNotBlank())sync();handler.postDelayed(periodicSync,60000L)};override fun onPause(){handler.removeCallbacks(periodicSync);super.onPause()};override fun onDestroy(){handler.removeCallbacks(clockTick);handler.removeCallbacks(periodicSync);executor.shutdownNow();super.onDestroy()}
 private fun buildUi(){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(42,26,42,30);setBackgroundColor(Color.rgb(9,11,15))};val top=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};logo=ImageView(this).apply{scaleType=ImageView.ScaleType.FIT_CENTER;setImageResource(R.drawable.ic_bbl)};top.addView(logo,LinearLayout.LayoutParams(92,72));title=TextView(this).apply{text=getString(R.string.app_name);textSize=30f;setTextColor(Color.WHITE);setTypeface(typeface,1);setPadding(16,0,10,0)};top.addView(title,LinearLayout.LayoutParams(0,-2,1f));clock=TextView(this).apply{textSize=18f;setTextColor(Color.WHITE);gravity=Gravity.END};top.addView(clock,LinearLayout.LayoutParams(280,-2));status=TextView(this).apply{textSize=15f;setTextColor(Color.LTGRAY);setPadding(0,8,0,16)};root.addView(top);root.addView(status);setContentView(root)}
 private fun clearContent(){while(root.childCount>2)root.removeViewAt(2)};private fun savedToken()=prefs.getString("device_token","")?:""
 private fun showActivation(message:String=""){clearContent();status.text="ID do dispositivo: $deviceId";val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(80,40,80,40)};box.addView(TextView(this).apply{text="ATIVAÇÃO BBL.BOXTV";textSize=26f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);setTypeface(typeface,1)});box.addView(TextView(this).apply{text=if(message.isBlank())"Digite o código gerado no painel" else message;textSize=17f;gravity=Gravity.CENTER;setTextColor(if(message.isBlank())Color.LTGRAY else Color.rgb(255,120,120));setPadding(0,12,0,18)});val code=EditText(this).apply{hint="BBL-XXXX-XXXX";textSize=22f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);setHintTextColor(Color.GRAY);isSingleLine=true};box.addView(code,LinearLayout.LayoutParams(-1,-2));val button=Button(this).apply{text="ATIVAR";textSize=20f;isAllCaps=false;isFocusable=true;setOnClickListener{activate(code.text.toString(),this,code)}};box.addView(button,LinearLayout.LayoutParams(-1,-2).apply{topMargin=18});root.addView(box,LinearLayout.LayoutParams(-1,-1));code.requestFocus()}
 private fun activate(code:String,button:Button,input:EditText){if(code.trim().isBlank()){Toast.makeText(this,"Digite o código de ativação",Toast.LENGTH_SHORT).show();return};button.isEnabled=false;status.text="Ativando • ID: $deviceId";(getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager).hideSoftInputFromWindow(input.windowToken,0);executor.execute{try{val token=ApiClient.enroll(deviceId,code);prefs.edit().putString("device_token",token).putString("activation_code",code.trim()).apply();val cfg=ApiClient.getPolicy(deviceId,token);runOnUiThread{render(cfg);Toast.makeText(this,"TV Box ativada",Toast.LENGTH_SHORT).show()}}catch(e:ApiClient.HttpStatusException){runOnUiThread{showActivation(if(e.code==403)"Código inválido ou desativado" else "Falha na ativação (HTTP ${e.code})")}}catch(_:Exception){runOnUiThread{showActivation("Servidor indisponível. Verifique a internet.")}}}}
 private fun sync(){val token=savedToken();if(token.isBlank()){showActivation();return};status.text="Sincronizando • ID: $deviceId";executor.execute{try{val cfg=ApiClient.getPolicy(deviceId,token);val cmds=try{ApiClient.getCommands(deviceId,token)}catch(_:Exception){emptyList()};runOnUiThread{render(cfg);handleCommands(cmds,token)}}catch(e:ApiClient.HttpStatusException){runOnUiThread{if(e.code==401){prefs.edit().remove("device_token").apply();showActivation("Ativação necessária")}else status.text="Falha no servidor (HTTP ${e.code}) • ID: $deviceId"}}catch(_:Exception){runOnUiThread{status.text="Servidor indisponível • ID: $deviceId"}}}}
 private fun render(cfg:DeviceConfig){currentApps=cfg.apps;clearContent();title.text=cfg.brandingName.ifBlank{getString(R.string.app_name)};applyBranding(cfg);if(!cfg.active){status.text="ACESSO BLOQUEADO • ID: $deviceId";root.addView(TextView(this).apply{text="Este aparelho está bloqueado ou com a validade encerrada.\nEntre em contato com o administrador.";textSize=24f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);setPadding(20,100,20,20)},LinearLayout.LayoutParams(-1,-1));return};status.text="ATIVO${if(cfg.expiresAt.isNotBlank())" • validade: ${cfg.expiresAt.take(10)}" else ""} • ID: $deviceId";if(cfg.message.isNotBlank()){root.addView(TextView(this).apply{text=cfg.message;textSize=17f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);setBackgroundColor(Color.argb(150,20,20,20));setPadding(18,10,18,10)},LinearLayout.LayoutParams(-1,-2).apply{bottomMargin=10});if(cfg.message!=lastMessage){lastMessage=cfg.message;AlertDialog.Builder(this).setTitle(cfg.brandingName).setMessage(cfg.message).setPositiveButton("OK",null).show()}};showBanner(cfg.banners.firstOrNull());val scroll=HorizontalScrollView(this).apply{isFillViewport=true};val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};cfg.apps.forEach{app->val installedCode=installedVersionCode(app.packageName);val installed=installedCode!=null;val needsUpdate=installed&&app.versionCode>0L&&installedCode!!<app.versionCode;val caption=when{needsUpdate->"${app.label}\nATUALIZAR";installed->app.label;else->"${app.label}\nINSTALAR"};val b=Button(this).apply{text=caption;textSize=18f;isAllCaps=false;isFocusable=true;setPadding(24,24,24,24);setOnClickListener{if(installed&&!needsUpdate)launchPackage(app.packageName)else requestInstall(app,true)};setOnFocusChangeListener{v,f->v.animate().scaleX(if(f)1.08f else 1f).scaleY(if(f)1.08f else 1f).setDuration(120).start()}};row.addView(b,LinearLayout.LayoutParams(280,160).apply{setMargins(10,10,10,10)})};if(cfg.apps.isEmpty())row.addView(TextView(this).apply{text="Nenhum aplicativo liberado pelo painel.";textSize=20f;setTextColor(Color.WHITE)})else row.getChildAt(0)?.requestFocus();scroll.addView(row);root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));maybeAutoInstall(cfg.apps)}
 private fun applyBranding(cfg:DeviceConfig){if(cfg.wallpaperUrl!=lastWallpaper){lastWallpaper=cfg.wallpaperUrl;if(cfg.wallpaperUrl.isBlank())root.setBackgroundColor(Color.rgb(9,11,15))else executor.execute{try{val bytes=ApiClient.downloadBytes(cfg.wallpaperUrl);val bmp=BitmapFactory.decodeByteArray(bytes,0,bytes.size);runOnUiThread{if(bmp!=null)root.background=BitmapDrawable(resources,bmp)}}catch(_:Exception){}}};if(cfg.logoUrl!=lastLogo){lastLogo=cfg.logoUrl;if(cfg.logoUrl.isBlank())logo.setImageResource(R.drawable.ic_bbl)else executor.execute{try{val bytes=ApiClient.downloadBytes(cfg.logoUrl);val bmp=BitmapFactory.decodeByteArray(bytes,0,bytes.size);runOnUiThread{if(bmp!=null)logo.setImageBitmap(bmp)}}catch(_:Exception){}}}}
 private fun installedVersionCode(pkg:String):Long?=try{val i=packageManager.getPackageInfo(pkg,0);if(Build.VERSION.SDK_INT>=28)i.longVersionCode else @Suppress("DEPRECATION") i.versionCode.toLong()}catch(_:Exception){null};private fun isAppCurrent(app:RemoteApp):Boolean{val installed=installedVersionCode(app.packageName)?:return false;return app.versionCode<=0L||installed>=app.versionCode}
 private fun maybeAutoInstall(apps:List<RemoteApp>){if(installBusy)return;val target=apps.firstOrNull{!isAppCurrent(it)&&it.downloadUrl.isNotBlank()}?:return;val key="${target.packageName}:${target.versionCode}:${target.sha256}";if(prefs.getString("last_auto_install_key","")==key)return;prefs.edit().putString("last_auto_install_key",key).apply();requestInstall(target,false)}
 private fun requestInstall(app:RemoteApp,manual:Boolean){if(installBusy)return;if(app.downloadUrl.isBlank()){Toast.makeText(this,"Este aplicativo não possui APK no painel",Toast.LENGTH_LONG).show();return};if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O&&!packageManager.canRequestPackageInstalls()){Toast.makeText(this,"Autorize BBL.BOXTV a instalar aplicativos",Toast.LENGTH_LONG).show();try{startActivity(Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:$packageName"))}catch(_:Exception){startActivity(Intent(Settings.ACTION_SECURITY_SETTINGS))};return};installBusy=true;status.text="Baixando ${app.label}...";executor.execute{val file=File(cacheDir,"remote_apks/${app.packageName}-${app.versionCode.coerceAtLeast(0)}.apk");try{ApiClient.downloadApk(app,file);runOnUiThread{status.text="Preparando instalação de ${app.label}..."};installWithPackageInstaller(file,app)}catch(e:Exception){installBusy=false;runOnUiThread{status.text="Falha ao baixar ${app.label} • ID: $deviceId";Toast.makeText(this,"Não foi possível baixar o APK${if(manual)": ${e.message}" else ""}",Toast.LENGTH_LONG).show()}}}}
 private fun installWithPackageInstaller(apk:File,app:RemoteApp){try{val installer=packageManager.packageInstaller;val params=PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL).apply{setAppPackageName(app.packageName)};val sid=installer.createSession(params);installer.openSession(sid).use{session->apk.inputStream().use{input->session.openWrite("base.apk",0,apk.length()).use{out->input.copyTo(out);session.fsync(out)}};val callback=Intent(this,InstallResultReceiver::class.java).apply{putExtra("package_name",app.packageName);putExtra("app_label",app.label)};val flags=PendingIntent.FLAG_UPDATE_CURRENT or if(Build.VERSION.SDK_INT>=31)PendingIntent.FLAG_MUTABLE else 0;val pending=PendingIntent.getBroadcast(this,sid,callback,flags);session.commit(pending.intentSender)}}catch(e:Exception){installBusy=false;runOnUiThread{status.text="Falha ao iniciar instalação de ${app.label} • ID: $deviceId";Toast.makeText(this,"Falha ao abrir instalador: ${e.message}",Toast.LENGTH_LONG).show()}}}
 private fun showBanner(b:RemoteBanner?){if(b==null||b.url.isBlank())return;val url=ApiClient.absoluteUrl(b.url);if(b.type.equals("video",true)){val v=VideoView(this).apply{setVideoURI(Uri.parse(url));setOnPreparedListener{mp->mp.isLooping=true;start()}};root.addView(v,LinearLayout.LayoutParams(-1,220).apply{bottomMargin=10})}else{val image=ImageView(this).apply{scaleType=ImageView.ScaleType.CENTER_CROP};root.addView(image,LinearLayout.LayoutParams(-1,220).apply{bottomMargin=10});executor.execute{try{val bytes=ApiClient.downloadBytes(url);val bmp=BitmapFactory.decodeByteArray(bytes,0,bytes.size);runOnUiThread{if(bmp!=null)image.setImageBitmap(bmp)}}catch(_:Exception){}}}}
 private fun handleCommands(commands:List<RemoteCommand>,token:String){commands.forEach{cmd->var st="done";var detail="ok";try{when(cmd.command.uppercase()){ "SYNC","RELOAD"->detail="sincronizado";"CLEAR_CACHE"->{cacheDir.deleteRecursively();detail="cache limpo"};"OPEN_SETTINGS"->startActivity(Intent(Settings.ACTION_SETTINGS));"REBOOT_REQUEST"->{st="unsupported";detail="reinício requer permissão de sistema/root"};else->{st="unsupported";detail="comando desconhecido"}}}catch(e:Exception){st="error";detail=e.message?:"erro"};executor.execute{try{ApiClient.reportCommand(deviceId,token,cmd.id,st,detail)}catch(_:Exception){}}}}
 private fun launchPackage(pkg:String){packageManager.getLaunchIntentForPackage(pkg)?.let{startActivity(it)}?:currentApps.firstOrNull{it.packageName==pkg}?.let{requestInstall(it,true)}?:Toast.makeText(this,"Aplicativo não instalado",Toast.LENGTH_SHORT).show()}
}
internal object DeviceIdentity{fun get(context:Context):String{val p=context.getSharedPreferences("bbl",Context.MODE_PRIVATE);p.getString("device_id",null)?.let{return it};val a=Settings.Secure.getString(context.contentResolver,Settings.Secure.ANDROID_ID);val s=(a?.takeLast(8)?:UUID.randomUUID().toString().take(8)).uppercase();return "BOX-$s".also{p.edit().putString("device_id",it).apply()}}}
