package com.bbl.boxtv.launcherv4;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int blue=Color.rgb(20,90,210), dark=Color.rgb(2,8,20); LinearLayout root; TextView clock;
 public void onCreate(Bundle b){super.onCreate(b);build();}
 GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);g.setStroke(3,Color.argb(120,255,255,255));return g;}
 TextView txt(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 public void build(){
  root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,22,28,22);GradientDrawable screen=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(35,110,230),Color.rgb(12,45,120),Color.BLACK});root.setBackground(screen);
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView logo=txt("BBL.BOXTV",28);logo.setTypeface(null,1);top.addView(logo,new LinearLayout.LayoutParams(0,70,1));clock=txt("",18);clock.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);top.addView(clock,new LinearLayout.LayoutParams(340,70));root.addView(top);tick();
  LinearLayout hero=new LinearLayout(this);hero.setGravity(Gravity.CENTER);TextView banner=txt("BBL.BOXTV\nO FUTURO ESTÁ AQUI\n\nTUDO LIBERADO",34);banner.setGravity(Gravity.CENTER);banner.setTypeface(null,1);banner.setBackground(bg(Color.argb(90,0,0,0),18));hero.addView(banner,new LinearLayout.LayoutParams(0,330,15));
  LinearLayout right=new LinearLayout(this);right.setOrientation(LinearLayout.HORIZONTAL);right.addView(feature("UniTV"),new LinearLayout.LayoutParams(0,330,1));right.addView(feature("Tudo Liberado"),new LinearLayout.LayoutParams(0,330,1));hero.addView(right,new LinearLayout.LayoutParams(0,330,10));root.addView(hero,new LinearLayout.LayoutParams(-1,330));
  TextView section=txt("APLICATIVOS",18);section.setPadding(4,14,0,8);root.addView(section);
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);List<ResolveInfo> apps=apps();for(ResolveInfo r:apps){row.addView(card(r),new LinearLayout.LayoutParams(220,170));}hs.addView(row);root.addView(hs,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);if(row.getChildCount()>0)row.getChildAt(0).requestFocus();
 }
 View feature(String name){FrameLayout f=new FrameLayout(this);f.setPadding(10,10,10,10);f.setBackground(bg(Color.argb(110,0,0,0),18));f.setFocusable(true);ImageView iv=new ImageView(this);iv.setImageResource(com.bbl.boxtv.launcherv4.R.drawable.ic_bbl);iv.setScaleType(ImageView.ScaleType.CENTER_INSIDE);f.addView(iv,new FrameLayout.LayoutParams(-1,220,Gravity.TOP));TextView t=txt(name,22);t.setGravity(Gravity.CENTER);f.addView(t,new FrameLayout.LayoutParams(-1,80,Gravity.BOTTOM));f.setOnFocusChangeListener((v,x)->{v.setScaleX(x?1.06f:1);v.setScaleY(x?1.06f:1);((FrameLayout)v).setBackground(bg(x?Color.argb(220,40,130,255):Color.argb(110,0,0,0),18));});f.setOnClickListener(v->launchByLabel(name));return f;}
 View card(final ResolveInfo r){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(10,8,10,8);c.setBackground(bg(Color.argb(120,0,0,0),14));c.setFocusable(true);ImageView iv=new ImageView(this);iv.setImageDrawable(r.loadIcon(getPackageManager()));iv.setScaleType(ImageView.ScaleType.CENTER_INSIDE);c.addView(iv,new LinearLayout.LayoutParams(115,105));TextView n=txt(r.loadLabel(getPackageManager()).toString(),17);n.setGravity(Gravity.CENTER);c.addView(n,new LinearLayout.LayoutParams(-1,50));c.setOnFocusChangeListener((v,x)->{v.setScaleX(x?1.08f:1);v.setScaleY(x?1.08f:1);v.setBackground(bg(x?Color.argb(230,35,120,255):Color.argb(120,0,0,0),14));});c.setOnClickListener(v->{Intent i=getPackageManager().getLaunchIntentForPackage(r.activityInfo.packageName);if(i!=null)startActivity(i);});LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)c.getLayoutParams();return c;}
 List<ResolveInfo> apps(){Intent i=new Intent(Intent.ACTION_MAIN);i.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> all=getPackageManager().queryIntentActivities(i,0), out=new ArrayList<>();for(ResolveInfo r:all)if(!r.activityInfo.packageName.equals(getPackageName()))out.add(r);Collections.sort(out,(a,b)->score(b)-score(a));return out;}
 int score(ResolveInfo r){String s=r.loadLabel(getPackageManager()).toString().toLowerCase();if(s.contains("unitv"))return 100;if(s.contains("tudo"))return 90;if(s.contains("youtube"))return 70;if(s.contains("anydesk"))return 60;return 1;}
 void launchByLabel(String key){for(ResolveInfo r:apps()){String s=r.loadLabel(getPackageManager()).toString().toLowerCase();if(s.contains(key.toLowerCase().split(" ")[0])){Intent i=getPackageManager().getLaunchIntentForPackage(r.activityInfo.packageName);if(i!=null){startActivity(i);return;}}}}
 void tick(){new Handler().post(new Runnable(){public void run(){clock.setText(new SimpleDateFormat("EEE, dd MMM  HH:mm",new Locale("pt","BR")).format(new Date()));clock.postDelayed(this,30000);}});}
}
