package com.bbl.boxtv.launcherv4;

import android.app.*;import android.os.*;import android.provider.Settings;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;import java.net.*;import java.io.*;import org.json.*;

public class MainActivity extends Activity{
 FrameLayout root,banner; SharedPreferences prefs; TextView clock,date; Handler handler=new Handler(); BgView bgView; ImageView remoteBanner; final int BW=1280,BH=720;
 int X(int v){return Math.round(v*root.getWidth()/(float)BW);} int Y(int v){return Math.round(v*root.getHeight()/(float)BH);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(5894);prefs=getSharedPreferences("slots",0);build();}
 @Override protected void onResume(){super.onResume();handler.postDelayed(()->loadRemoteTheme(),1200);}
 @Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);super.onDestroy();}
 TextView txt(String s,float sp,int gravity){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.WHITE);t.setGravity(gravity);t.setShadowLayer(6,0,2,Color.BLACK);return t;}
 GradientDrawable panel(int fill,int stroke,int sw,int rad){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setStroke(sw,stroke);g.setCornerRadius(rad);return g;}
 void build(){root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);bgView=new BgView(this);root.addView(bgView,new FrameLayout.LayoutParams(-1,-1));setContentView(root);root.post(()->{layoutUI();loadCachedTheme();loadRemoteTheme();});}
 void layoutUI(){
  TextView logo=txt("BBL.BOX TV",34,Gravity.CENTER);logo.setTypeface(null,1);logo.setTextColor(Color.rgb(255,185,70));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(X(420),Y(54));lp.leftMargin=X(430);lp.topMargin=Y(14);root.addView(logo,lp);
  TextView sl=txt("O FUTURO ESTA AQUI",13,Gravity.CENTER);FrameLayout.LayoutParams sp=new FrameLayout.LayoutParams(X(360),Y(28));sp.leftMargin=X(460);sp.topMargin=Y(58);root.addView(sl,sp);
  clock=txt("",28,Gravity.RIGHT|Gravity.CENTER_VERTICAL);clock.setTypeface(null,1);FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(X(175),Y(42));cp.leftMargin=X(1080);cp.topMargin=Y(12);root.addView(clock,cp);
  date=txt("",12,Gravity.RIGHT|Gravity.CENTER_VERTICAL);FrameLayout.LayoutParams dp=new FrameLayout.LayoutParams(X(260),Y(28));dp.leftMargin=X(995);dp.topMargin=Y(49);root.addView(date,dp);startClock();
  addTop("Configuracoes",890,82,120,42,()->openSettings());addTop("Wi-Fi",1018,82,90,42,()->openWifi());addTop("Suporte",1116,82,120,42,()->openSupport());
  banner=new FrameLayout(this);banner.setBackground(panel(Color.argb(180,5,8,18),Color.rgb(80,210,255),2,18));FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(X(770),Y(330));bp.leftMargin=X(24);bp.topMargin=Y(132);root.addView(banner,bp);
  TextView b1=txt("BBL.BOX TV",55,Gravity.CENTER);b1.setTypeface(null,1);b1.setTextColor(Color.rgb(255,155,40));FrameLayout.LayoutParams b1p=new FrameLayout.LayoutParams(-1,Y(120));b1p.topMargin=Y(55);banner.addView(b1,b1p);
  TextView b2=txt("O MELHOR DO ENTRETENIMENTO EM UM SO LUGAR",17,Gravity.CENTER);b2.setTypeface(null,1);FrameLayout.LayoutParams b2p=new FrameLayout.LayoutParams(-1,Y(46));b2p.topMargin=Y(175);banner.addView(b2,b2p);
  LinearLayout cats=new LinearLayout(this);cats.setGravity(Gravity.CENTER);String[] cs={"FILMES","SERIES","ESPORTES","INFANTIL","MUSICA","CANAIS"};for(String c:cs){TextView t=txt(c,11,Gravity.CENTER);cats.addView(t,new LinearLayout.LayoutParams(0,-1,1));}FrameLayout.LayoutParams csp=new FrameLayout.LayoutParams(-1,Y(58),Gravity.BOTTOM);csp.leftMargin=X(12);csp.rightMargin=X(12);csp.bottomMargin=Y(12);banner.addView(cats,csp);
  remoteBanner=new ImageView(this);remoteBanner.setScaleType(ImageView.ScaleType.CENTER_CROP);remoteBanner.setLayerType(View.LAYER_TYPE_SOFTWARE,null);remoteBanner.setVisibility(View.GONE);banner.addView(remoteBanner,new FrameLayout.LayoutParams(-1,-1));
  addFeature("UniTV FREE","unitv",812,132,210,330);addFeature("TUDO LIBERADO","tudo",1034,132,222,330);
  int[] xs={24,232,440,648,856};for(int i=0;i<5;i++)addSlot(i,xs[i],486,196,185);addMyApps(1064,486,192,185);
  try{root.getChildAt(5).requestFocus();}catch(Exception e){}
 }
 void addTop(String s,int x,int y,int w,int h,Runnable r){TextView t=txt(s,12,Gravity.CENTER);t.setFocusable(true);t.setBackground(panel(Color.argb(185,4,10,26),Color.rgb(30,205,255),2,12));t.setOnFocusChangeListener((v,on)->{v.setScaleX(on?1.06f:1);v.setScaleY(on?1.06f:1);v.setBackground(panel(on?Color.argb(220,0,95,150):Color.argb(185,4,10,26),on?Color.CYAN:Color.rgb(30,205,255),on?4:2,12));});t.setOnClickListener(v->r.run());FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(X(w),Y(h));p.leftMargin=X(x);p.topMargin=Y(y);root.addView(t,p);}
 void addFeature(String label,String key,int x,int y,int w,int h){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setFocusable(true);box.setPadding(X(10),Y(10),X(10),Y(10));box.setBackground(panel(Color.argb(210,9,15,48),Color.rgb(70,215,255),2,18));ResolveInfo r=findApp(key);ImageView iv=new ImageView(this);iv.setScaleType(ImageView.ScaleType.CENTER_INSIDE);if(r!=null)iv.setImageDrawable(r.loadIcon(getPackageManager()));else iv.setImageResource(R.drawable.ic_bbl);box.addView(iv,new LinearLayout.LayoutParams(X(135),0,1));TextView tv=txt(label,16,Gravity.CENTER);tv.setTypeface(null,1);box.addView(tv,new LinearLayout.LayoutParams(-1,Y(48)));box.setOnClickListener(v->launchPreferred(key));box.setOnFocusChangeListener((v,on)->{v.setScaleX(on?1.04f:1);v.setScaleY(on?1.04f:1);v.setBackground(panel(on?Color.argb(230,8,70,140):Color.argb(210,9,15,48),on?Color.CYAN:Color.rgb(70,215,255),on?4:2,18));});FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(X(w),Y(h));p.leftMargin=X(x);p.topMargin=Y(y);root.addView(box,p);}
 void addSlot(int idx,int x,int y,int w,int h){String pkg=prefs.getString("slot"+idx,"");FrameLayout box=new FrameLayout(this);box.setFocusable(true);box.setBackground(panel(Color.argb(205,10,14,45),Color.rgb(70,130,255),2,16));FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(X(w),Y(h));p.leftMargin=X(x);p.topMargin=Y(y);root.addView(box,p);if(pkg.length()>0)fillSlot(box,pkg);else{TextView plus=txt("+",58,Gravity.CENTER);plus.setTypeface(null,1);box.addView(plus,new FrameLayout.LayoutParams(-1,-1));}box.setOnClickListener(v->{String cur=prefs.getString("slot"+idx,"");if(cur.length()==0)pickApp(idx);else launchPackage(cur);});box.setOnLongClickListener(v->{slotOptions(idx);return true;});box.setOnFocusChangeListener((v,on)->{v.setScaleX(on?1.05f:1);v.setScaleY(on?1.05f:1);v.setBackground(panel(on?Color.argb(235,8,65,125):Color.argb(205,10,14,45),on?Color.CYAN:Color.rgb(70,130,255),on?4:2,16));});}
 void addMyApps(int x,int y,int w,int h){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setFocusable(true);box.setBackground(panel(Color.argb(205,10,14,45),Color.rgb(70,130,255),2,16));TextView icon=txt("[ ] [ ]\n[ ] [ ]",28,Gravity.CENTER);TextView label=txt("Meus Apps",16,Gravity.CENTER);box.addView(icon,new LinearLayout.LayoutParams(-1,0,1));box.addView(label,new LinearLayout.LayoutParams(-1,Y(48)));box.setOnClickListener(v->showAllApps());box.setOnFocusChangeListener((v,on)->{v.setScaleX(on?1.05f:1);v.setScaleY(on?1.05f:1);v.setBackground(panel(on?Color.argb(235,8,65,125):Color.argb(205,10,14,45),on?Color.CYAN:Color.rgb(70,130,255),on?4:2,16));});FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(X(w),Y(h));p.leftMargin=X(x);p.topMargin=Y(y);root.addView(box,p);}
 void fillSlot(FrameLayout box,String pkg){try{PackageManager pm=getPackageManager();ApplicationInfo ai=pm.getApplicationInfo(pkg,0);LinearLayout ll=new LinearLayout(this);ll.setOrientation(LinearLayout.VERTICAL);ll.setGravity(Gravity.CENTER);ImageView iv=new ImageView(this);iv.setImageDrawable(pm.getApplicationIcon(pkg));iv.setScaleType(ImageView.ScaleType.CENTER_INSIDE);TextView tv=txt(pm.getApplicationLabel(ai).toString(),14,Gravity.CENTER);ll.addView(iv,new LinearLayout.LayoutParams(X(92),0,1));ll.addView(tv,new LinearLayout.LayoutParams(-1,Y(40)));box.addView(ll,new FrameLayout.LayoutParams(-1,-1));}catch(Exception e){}}
 List<ResolveInfo> apps(){Intent i=new Intent(Intent.ACTION_MAIN);i.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo>a=getPackageManager().queryIntentActivities(i,0),o=new ArrayList<>();for(ResolveInfo r:a)if(!r.activityInfo.packageName.equals(getPackageName()))o.add(r);Collections.sort(o,(a1,b1)->a1.loadLabel(getPackageManager()).toString().compareToIgnoreCase(b1.loadLabel(getPackageManager()).toString()));return o;}
 ResolveInfo findApp(String key){for(ResolveInfo r:apps()){String s=(r.loadLabel(getPackageManager())+" "+r.activityInfo.packageName).toLowerCase();if(s.contains(key))return r;}return null;}
 void launchPreferred(String key){ResolveInfo r=findApp(key);if(r!=null)launchPackage(r.activityInfo.packageName);else Toast.makeText(this,"Aplicativo nao instalado",Toast.LENGTH_SHORT).show();}
 void pickApp(final int idx){final List<ResolveInfo>a=apps();String[] n=new String[a.size()];for(int i=0;i<a.size();i++)n[i]=a.get(i).loadLabel(getPackageManager()).toString();new AlertDialog.Builder(this).setTitle("Escolher aplicativo").setItems(n,(d,w)->{prefs.edit().putString("slot"+idx,a.get(w).activityInfo.packageName).apply();recreate();}).setNegativeButton("Cancelar",null).show();}
 void slotOptions(final int idx){String pkg=prefs.getString("slot"+idx,"");if(pkg.length()==0){pickApp(idx);return;}new AlertDialog.Builder(this).setTitle("Atalho").setItems(new String[]{"Trocar aplicativo","Remover atalho"},(d,w)->{if(w==0)pickApp(idx);else{prefs.edit().remove("slot"+idx).apply();recreate();}}).show();}
 void showAllApps(){final List<ResolveInfo>a=apps();String[] n=new String[a.size()];for(int i=0;i<a.size();i++)n[i]=a.get(i).loadLabel(getPackageManager()).toString();new AlertDialog.Builder(this).setTitle("Meus Apps").setItems(n,(d,w)->launchPackage(a.get(w).activityInfo.packageName)).setNegativeButton("Fechar",null).show();}
 void launchPackage(String pkg){try{Intent i=getPackageManager().getLaunchIntentForPackage(pkg);if(i!=null)startActivity(i);}catch(Exception e){}}
 void openSettings(){try{startActivity(new Intent(Settings.ACTION_SETTINGS));}catch(Exception e){}}
 void openWifi(){try{startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));}catch(Exception e){openSettings();}}
 void openSupport(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/5521988510594")));}catch(Exception e){}}
 void startClock(){handler.post(new Runnable(){public void run(){Date d=new Date();clock.setText(new SimpleDateFormat("HH:mm:ss",new Locale("pt","BR")).format(d));date.setText(new SimpleDateFormat("EEE, dd 'de' MMM 'de' yyyy",new Locale("pt","BR")).format(d));handler.postDelayed(this,1000);}});}
 String abs(String u){if(u==null||u.trim().length()==0)return "";u=u.trim();if(u.startsWith("http://")||u.startsWith("https://"))return u;return BuildConfig.API_BASE_URL.replaceAll("/$","")+"/"+u.replaceFirst("^/","");}
 byte[] getBytes(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setInstanceFollowRedirects(true);c.setRequestProperty("Accept","image/*,*/*");try{if(c.getResponseCode()<200||c.getResponseCode()>299)throw new IOException("HTTP "+c.getResponseCode());ByteArrayOutputStream o=new ByteArrayOutputStream();InputStream in=c.getInputStream();byte[] b=new byte[16384];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toByteArray();}finally{c.disconnect();}}
 Bitmap decode(byte[] data){try{BitmapFactory.Options o=new BitmapFactory.Options();o.inPreferredConfig=Bitmap.Config.RGB_565;o.inDither=true;return BitmapFactory.decodeByteArray(data,0,data.length,o);}catch(Exception e){return null;}}
 void saveCache(String name,byte[] data){try{FileOutputStream f=openFileOutput(name,MODE_PRIVATE);f.write(data);f.close();}catch(Exception e){}}
 Bitmap loadCache(String name){try{FileInputStream f=openFileInput(name);BitmapFactory.Options o=new BitmapFactory.Options();o.inPreferredConfig=Bitmap.Config.RGB_565;o.inDither=true;Bitmap b=BitmapFactory.decodeStream(f,null,o);f.close();return b;}catch(Exception e){return null;}}
 void loadCachedTheme(){Bitmap w=loadCache("panel_wallpaper.img");if(w!=null)bgView.setRemote(w);Bitmap b=loadCache("panel_banner.img");if(b!=null&&remoteBanner!=null){remoteBanner.setImageBitmap(b);remoteBanner.setVisibility(View.VISIBLE);}}
 void loadRemoteTheme(){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BuildConfig.API_BASE_URL+"/api/launcher-v4/theme").openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setRequestProperty("Accept","application/json");String text;try{if(c.getResponseCode()!=200)return;BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);r.close();text=s.toString();}finally{c.disconnect();}JSONObject j=new JSONObject(text);String wu=abs(j.optString("wallpaper_url",""));String bu=abs(j.optString("banner_url",""));final Bitmap[] wb={null};final Bitmap[] bb={null};if(wu.length()>0){byte[] d=getBytes(wu);saveCache("panel_wallpaper.img",d);wb[0]=decode(d);}if(bu.length()>0){byte[] d=getBytes(bu);saveCache("panel_banner.img",d);bb[0]=decode(d);}runOnUiThread(()->{if(wb[0]!=null)bgView.setRemote(wb[0]);if(remoteBanner!=null){if(bb[0]!=null){remoteBanner.setImageBitmap(bb[0]);remoteBanner.setVisibility(View.VISIBLE);}else if(bu.length()==0)remoteBanner.setVisibility(View.GONE);}});}catch(Exception e){}finally{handler.postDelayed(()->loadRemoteTheme(),60000);}}).start();}
 class BgView extends View{Paint p=new Paint(3);Bitmap remote;public BgView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}void setRemote(Bitmap b){remote=b;invalidate();}protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();LinearGradient g=new LinearGradient(0,0,w,h,new int[]{Color.rgb(2,4,15),Color.rgb(8,15,55),Color.rgb(35,3,12),Color.BLACK},null,Shader.TileMode.CLAMP);p.setShader(g);c.drawRect(0,0,w,h,p);p.setShader(null);if(remote!=null&&!remote.isRecycled()){float s=Math.max(w/(float)remote.getWidth(),h/(float)remote.getHeight());int dw=Math.round(remote.getWidth()*s),dh=Math.round(remote.getHeight()*s),l=(w-dw)/2,t=(h-dh)/2;Rect dst=new Rect(l,t,l+dw,t+dh);p.setFilterBitmap(true);p.setDither(true);c.drawBitmap(remote,null,dst,p);return;}p.setStrokeWidth(Math.max(2,h/300));for(int i=0;i<10;i++){p.setColor(Color.argb(70,15,80+i*12,255));c.drawLine(0,i*h/10,w,(i*h/10)+h/7,p);}for(int i=0;i<7;i++){p.setColor(Color.argb(80,255,30+i*15,10));c.drawLine(w,i*h/7,0,(i*h/7)+h/4,p);}RadialGradient r=new RadialGradient(w/2,h/2,Math.max(w,h)/2,new int[]{Color.argb(105,255,70,0),Color.TRANSPARENT},null,Shader.TileMode.CLAMP);p.setShader(r);c.drawRect(0,0,w,h,p);p.setShader(null);}}
}
