plugins { id 'com.android.application' }

android { namespace 'com.bbl.boxtv.launcherv4'; compileSdk 35
  defaultConfig {
    applicationId 'com.bbl.boxtv.launcherv4'
    minSdk 21
    targetSdk 28
    versionCode 4
    versionName '4.3-base2-tudo'
    buildConfigField 'String', 'API_BASE_URL', '"https://bbl-tvbox-manager-v2.onrender.com"'
  }
  buildFeatures { buildConfig true }
}
