plugins { id 'com.android.application' }

android { namespace 'com.bbl.boxtv.launcherv4'; compileSdk 35
  defaultConfig {
    applicationId 'com.bbl.boxtv.telalauncher'
    minSdk 21
    targetSdk 28
    versionCode 10
    versionName '1.3.0-v4-bundled-exact-apps'
    buildConfigField 'String', 'API_BASE_URL', '"https://bbl-tvbox-manager-v2.onrender.com"'
  }
  buildFeatures { buildConfig true }
}


dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
